CREATE TABLE sys_role (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role_code VARCHAR(64) NOT NULL UNIQUE,
    role_name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    role_code VARCHAR(64) NOT NULL,
    enabled BIT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE dict_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dict_type VARCHAR(64) NOT NULL,
    item_key VARCHAR(64) NOT NULL,
    item_label VARCHAR(128) NOT NULL,
    sort_order INT NOT NULL,
    enabled BIT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_dict_item (dict_type, item_key)
);

CREATE TABLE enterprise (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    contact_person VARCHAR(64),
    phone VARCHAR(64),
    service_area VARCHAR(255),
    service_items VARCHAR(500),
    service_modes VARCHAR(128),
    response_speed VARCHAR(64),
    certification_status VARCHAR(64),
    certification_level VARCHAR(64),
    expertise VARCHAR(255),
    case_experience VARCHAR(255),
    price_range VARCHAR(128),
    service_time VARCHAR(128),
    willing_to_take BIT,
    special_limit VARCHAR(255),
    active BIT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE customer_lead (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_no VARCHAR(32) NOT NULL UNIQUE,
    entry_date DATE,
    customer_name VARCHAR(64) NOT NULL,
    contact_phone VARCHAR(64) NOT NULL,
    city_area VARCHAR(128),
    age_range VARCHAR(64),
    family_structure VARCHAR(255),
    source_channel VARCHAR(64),
    referrer_name VARCHAR(64),
    channel_trust_level VARCHAR(64),
    service_object VARCHAR(64),
    initial_need_type VARCHAR(64),
    service_preference VARCHAR(64),
    urgency VARCHAR(64),
    clear_pain_point BIT,
    strong_trust_demand BIT,
    budget_range VARCHAR(128),
    decision_maker VARCHAR(64),
    decision_speed VARCHAR(64),
    price_sensitivity VARCHAR(64),
    certification_interest VARCHAR(64),
    customer_level VARCHAR(32),
    current_status VARCHAR(32),
    workflow_stage VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    owner_name VARCHAR(64),
    follow_up_at DATETIME,
    remark TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE lead_identification (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    channel_trust_level VARCHAR(64),
    service_object VARCHAR(64),
    initial_need_type VARCHAR(64),
    service_preference VARCHAR(64),
    urgency VARCHAR(64),
    clear_pain_point BIT,
    strong_trust_demand BIT,
    budget_range VARCHAR(128),
    decision_maker VARCHAR(64),
    decision_speed VARCHAR(64),
    price_sensitivity VARCHAR(64),
    certification_interest VARCHAR(64),
    customer_level VARCHAR(32),
    current_status VARCHAR(32),
    follow_up_at DATETIME,
    owner_name VARCHAR(64),
    remark TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE need_assessment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    assessment_date DATE,
    assessor_name VARCHAR(64),
    main_issue TEXT,
    background_info TEXT,
    need_duration VARCHAR(64),
    goal_type VARCHAR(64),
    service_mode VARCHAR(64),
    service_time_preference VARCHAR(128),
    service_frequency VARCHAR(128),
    privacy_requirement VARCHAR(255),
    environment_requirement VARCHAR(255),
    staff_requirement VARCHAR(255),
    risk_concern VARCHAR(128),
    accept_platform_match BIT,
    need_platform_supervision BIT,
    bad_service_experience BIT,
    budget_range VARCHAR(128),
    decision_mode VARCHAR(64),
    start_mode VARCHAR(64),
    platform_conclusion TEXT,
    recommended_service_mode VARCHAR(64),
    recommended_cycle VARCHAR(128),
    recommended_enterprise_type VARCHAR(128),
    risk_tip TEXT,
    enter_match_flow BIT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE enterprise_match (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    need_type VARCHAR(64),
    service_mode VARCHAR(64),
    budget_range VARCHAR(128),
    special_requirements TEXT,
    primary_enterprise_id BIGINT,
    backup_enterprise_id BIGINT,
    recommendation_reason TEXT,
    other_not_recommended_reason TEXT,
    enterprise_confirmed BIT,
    customer_accepted BIT,
    final_enterprise_id BIGINT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE enterprise_match_candidate (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    match_id BIGINT NOT NULL,
    slot_code VARCHAR(8) NOT NULL,
    enterprise_id BIGINT,
    enterprise_name VARCHAR(128),
    contact_person VARCHAR(64),
    phone VARCHAR(64),
    service_area VARCHAR(255),
    service_items VARCHAR(500),
    service_modes VARCHAR(128),
    response_speed VARCHAR(64),
    certification_status VARCHAR(64),
    certification_level VARCHAR(64),
    expertise VARCHAR(255),
    case_experience VARCHAR(255),
    fit_score INT,
    price_range VARCHAR(128),
    service_time VARCHAR(128),
    willing_to_take BIT,
    special_limit VARCHAR(255),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE delivery_supervision (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    service_enterprise VARCHAR(128),
    service_project VARCHAR(128),
    service_mode VARCHAR(64),
    service_date DATE,
    service_time VARCHAR(64),
    coordinator_name VARCHAR(64),
    customer_confirmed BIT,
    enterprise_confirmed BIT,
    staff_confirmed BIT,
    location_confirmed BIT,
    special_need_confirmed BIT,
    risk_informed BIT,
    started_on_time BIT,
    staff_on_site BIT,
    executed_as_agreed BIT,
    has_exception BIT,
    exception_content TEXT,
    resolution TEXT,
    handler_name VARCHAR(64),
    follow_up_time DATETIME,
    follow_up_by VARCHAR(64),
    satisfaction_score INT,
    most_satisfied_point VARCHAR(255),
    most_dissatisfied_point VARCHAR(255),
    need_adjustment BIT,
    willing_continue BIT,
    willing_recommend BIT,
    met_standard BIT,
    enterprise_performance_level VARCHAR(64),
    continue_cooperation BIT,
    next_action TEXT,
    remark TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE after_sales_followup (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    first_deal_date DATE,
    first_enterprise VARCHAR(128),
    first_service_project VARCHAR(128),
    first_satisfaction VARCHAR(64),
    platform_recognition VARCHAR(64),
    enterprise_recognition VARCHAR(64),
    has_new_demand BIT,
    other_family_demand BIT,
    repurchase_possibility VARCHAR(64),
    repurchase_direction VARCHAR(64),
    recommended_plan TEXT,
    recommended_communication_time DATETIME,
    recommended_communication_person VARCHAR(64),
    willing_referral BIT,
    potential_referral_target VARCHAR(255),
    referral_progress VARCHAR(255),
    new_lead_created BIT,
    customer_lifecycle_status VARCHAR(64),
    next_contact_time DATETIME,
    long_term_owner VARCHAR(64),
    remark TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE public_form_token (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    token VARCHAR(128) NOT NULL UNIQUE,
    form_type VARCHAR(32) NOT NULL,
    lead_id BIGINT NOT NULL,
    order_no VARCHAR(32),
    expire_at DATETIME NOT NULL,
    used_flag BIT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE operation_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    entity_type VARCHAR(64) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(64) NOT NULL,
    operator_name VARCHAR(64),
    detail TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);
